package clients

import (
	"github.com/CloudSilk/CloudSilk/pkg/proto"
)

var ProductionStationClient = new(proto.ProductionStationClientImpl)
var ProductionStationSignupClient = new(proto.ProductionStationSignupClientImpl)
var ProductionLineClient = new(proto.ProductionLineClientImpl)
var ProductAttributeClient = new(proto.ProductAttributeClientImpl)
var ProductionCrosswayClient = new(proto.ProductionCrosswayClientImpl)
var MaterialTrayClient = new(proto.MaterialTrayClientImpl)
var MaterialTrayBindingRecordClient = new(proto.MaterialTrayBindingRecordClientImpl)
var MaterialChannelLayerClient = new(proto.MaterialChannelLayerClientImpl)
var ProductPackageRecordClient = new(proto.ProductPackageRecordClientImpl)
var ProductInfoClient = new(proto.ProductInfoClientImpl)
var ProductOrderClient = new(proto.ProductOrderClientImpl)
var ProductRhythmRecordClient = new(proto.ProductRhythmRecordClientImpl)
var ProductProcessRouteClient = new(proto.ProductProcessRouteClientImpl)
var ProductionProcessClient = new(proto.ProductionProcessClientImpl)
var ProductionProcessSopClient = new(proto.ProductionProcessSopClientImpl)
var ProductModelClient = new(proto.ProductModelClientImpl)
var PersonnelQualificationClient = new(proto.PersonnelQualificationClientImpl)
var SystemEventClient = new(proto.SystemEventClientImpl)
var SystemEventTriggerClient = new(proto.SystemEventTriggerClientImpl)
var SystemEventTriggerParameterClient = new(proto.SystemEventTriggerParameterClientImpl)
var ProductReworkRecordClient = new(proto.ProductReworkRecordClientImpl)
var ProductOrderProcessClient = new(proto.ProductOrderProcessClientImpl)
var ProductOrderBomClient = new(proto.ProductOrderBomClientImpl)
var ProductionStationOutputClient = new(proto.ProductionStationOutputClientImpl)
var ProductOrderAttributeClient = new(proto.ProductOrderAttributeClientImpl)
var ProcessStepParameterClient = new(proto.ProcessStepParameterClientImpl)
var ProductionProcessStepClient = new(proto.ProductionProcessStepClientImpl)
var ProductTestRecordClient = new(proto.ProductTestRecordClientImpl)
var ProductWorkRecordClient = new(proto.ProductWorkRecordClientImpl)
var ProductOrderProcessStepClient = new(proto.ProductOrderProcessStepClientImpl)
