// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: agv_task_type.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AGVTaskTypeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// 代号
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	// 描述
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	// 货架类型
	ShelfType int32 `protobuf:"varint,4,opt,name=shelfType,proto3" json:"shelfType"`
	// 场景类型
	SceneType int32 `protobuf:"varint,5,opt,name=sceneType,proto3" json:"sceneType"`
	// 任务点位
	PositionCode string `protobuf:"bytes,6,opt,name=positionCode,proto3" json:"positionCode"`
	// 备注
	Remark string `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark"`
	// 容器类型ID
	MaterialContainerTypeID string                     `protobuf:"bytes,8,opt,name=materialContainerTypeID,proto3" json:"materialContainerTypeID"`
	MaterialContainerType   *MaterialContainerTypeInfo `protobuf:"bytes,9,opt,name=materialContainerType,proto3" json:"materialContainerType"`
}

func (x *AGVTaskTypeInfo) Reset() {
	*x = AGVTaskTypeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agv_task_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AGVTaskTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AGVTaskTypeInfo) ProtoMessage() {}

func (x *AGVTaskTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agv_task_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AGVTaskTypeInfo.ProtoReflect.Descriptor instead.
func (*AGVTaskTypeInfo) Descriptor() ([]byte, []int) {
	return file_agv_task_type_proto_rawDescGZIP(), []int{0}
}

func (x *AGVTaskTypeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AGVTaskTypeInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AGVTaskTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AGVTaskTypeInfo) GetShelfType() int32 {
	if x != nil {
		return x.ShelfType
	}
	return 0
}

func (x *AGVTaskTypeInfo) GetSceneType() int32 {
	if x != nil {
		return x.SceneType
	}
	return 0
}

func (x *AGVTaskTypeInfo) GetPositionCode() string {
	if x != nil {
		return x.PositionCode
	}
	return ""
}

func (x *AGVTaskTypeInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AGVTaskTypeInfo) GetMaterialContainerTypeID() string {
	if x != nil {
		return x.MaterialContainerTypeID
	}
	return ""
}

func (x *AGVTaskTypeInfo) GetMaterialContainerType() *MaterialContainerTypeInfo {
	if x != nil {
		return x.MaterialContainerType
	}
	return nil
}

type QueryAGVTaskTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: uri:"pageIndex" form:"pageIndex"
	PageIndex int64 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex" uri:"pageIndex" form:"pageIndex"`
	// @inject_tag: uri:"pageSize" form:"pageSize"
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize" uri:"pageSize" form:"pageSize"`
	// @inject_tag: uri:"sortConfig" form:"sortConfig"
	SortConfig string `protobuf:"bytes,3,opt,name=sortConfig,proto3" json:"sortConfig" uri:"sortConfig" form:"sortConfig"`
	// 货架类型
	// @inject_tag: uri:"shelfType" form:"shelfType"
	ShelfType int32 `protobuf:"varint,4,opt,name=shelfType,proto3" json:"shelfType" uri:"shelfType" form:"shelfType"`
	// 场景类型
	// @inject_tag: uri:"sceneType" form:"sceneType"
	SceneType int32 `protobuf:"varint,5,opt,name=sceneType,proto3" json:"sceneType" uri:"sceneType" form:"sceneType"`
	// 容器类型ID
	// @inject_tag: uri:"materialContainerTypeID" form:"materialContainerTypeID"
	MaterialContainerTypeID string `protobuf:"bytes,6,opt,name=materialContainerTypeID,proto3" json:"materialContainerTypeID" uri:"materialContainerTypeID" form:"materialContainerTypeID"`
}

func (x *QueryAGVTaskTypeRequest) Reset() {
	*x = QueryAGVTaskTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agv_task_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAGVTaskTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAGVTaskTypeRequest) ProtoMessage() {}

func (x *QueryAGVTaskTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agv_task_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAGVTaskTypeRequest.ProtoReflect.Descriptor instead.
func (*QueryAGVTaskTypeRequest) Descriptor() ([]byte, []int) {
	return file_agv_task_type_proto_rawDescGZIP(), []int{1}
}

func (x *QueryAGVTaskTypeRequest) GetPageIndex() int64 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *QueryAGVTaskTypeRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryAGVTaskTypeRequest) GetSortConfig() string {
	if x != nil {
		return x.SortConfig
	}
	return ""
}

func (x *QueryAGVTaskTypeRequest) GetShelfType() int32 {
	if x != nil {
		return x.ShelfType
	}
	return 0
}

func (x *QueryAGVTaskTypeRequest) GetSceneType() int32 {
	if x != nil {
		return x.SceneType
	}
	return 0
}

func (x *QueryAGVTaskTypeRequest) GetMaterialContainerTypeID() string {
	if x != nil {
		return x.MaterialContainerTypeID
	}
	return ""
}

type QueryAGVTaskTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code               `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code"`
	Message string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    []*AGVTaskTypeInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
	Pages   int64              `protobuf:"varint,4,opt,name=pages,proto3" json:"pages"`
	Records int64              `protobuf:"varint,5,opt,name=records,proto3" json:"records"`
	Total   int64              `protobuf:"varint,6,opt,name=total,proto3" json:"total"`
}

func (x *QueryAGVTaskTypeResponse) Reset() {
	*x = QueryAGVTaskTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agv_task_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAGVTaskTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAGVTaskTypeResponse) ProtoMessage() {}

func (x *QueryAGVTaskTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agv_task_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAGVTaskTypeResponse.ProtoReflect.Descriptor instead.
func (*QueryAGVTaskTypeResponse) Descriptor() ([]byte, []int) {
	return file_agv_task_type_proto_rawDescGZIP(), []int{2}
}

func (x *QueryAGVTaskTypeResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *QueryAGVTaskTypeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryAGVTaskTypeResponse) GetData() []*AGVTaskTypeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryAGVTaskTypeResponse) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *QueryAGVTaskTypeResponse) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

func (x *QueryAGVTaskTypeResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAllAGVTaskTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code               `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code"`
	Message string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    []*AGVTaskTypeInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
}

func (x *GetAllAGVTaskTypeResponse) Reset() {
	*x = GetAllAGVTaskTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agv_task_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllAGVTaskTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAGVTaskTypeResponse) ProtoMessage() {}

func (x *GetAllAGVTaskTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agv_task_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAGVTaskTypeResponse.ProtoReflect.Descriptor instead.
func (*GetAllAGVTaskTypeResponse) Descriptor() ([]byte, []int) {
	return file_agv_task_type_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllAGVTaskTypeResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *GetAllAGVTaskTypeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllAGVTaskTypeResponse) GetData() []*AGVTaskTypeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAGVTaskTypeDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code             `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code"`
	Message string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    *AGVTaskTypeInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (x *GetAGVTaskTypeDetailResponse) Reset() {
	*x = GetAGVTaskTypeDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agv_task_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAGVTaskTypeDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAGVTaskTypeDetailResponse) ProtoMessage() {}

func (x *GetAGVTaskTypeDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agv_task_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAGVTaskTypeDetailResponse.ProtoReflect.Descriptor instead.
func (*GetAGVTaskTypeDetailResponse) Descriptor() ([]byte, []int) {
	return file_agv_task_type_proto_rawDescGZIP(), []int{4}
}

func (x *GetAGVTaskTypeDetailResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *GetAGVTaskTypeDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAGVTaskTypeDetailResponse) GetData() *AGVTaskTypeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_agv_task_type_proto protoreflect.FileDescriptor

var file_agv_task_type_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x67, 0x76, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x6d, 0x6f,
	0x6d, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d,
	0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x02,
	0x0a, 0x0f, 0x41, 0x47, 0x56, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x65, 0x6c, 0x66,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x68, 0x65, 0x6c,
	0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12,
	0x38, 0x0a, 0x17, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x17, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x12, 0x56, 0x0a, 0x15, 0x6d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x15, 0x6d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x22, 0xe9, 0x01, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x47, 0x56, 0x54, 0x61,
	0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x72,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x65, 0x6c, 0x66,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x68, 0x65, 0x6c,
	0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x17, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x22, 0xc7, 0x01,
	0x0a, 0x18, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x47, 0x56, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x47, 0x56, 0x54,
	0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x82, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x41, 0x47, 0x56, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x47, 0x56, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x85, 0x01, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x41, 0x47, 0x56, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x47, 0x56, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agv_task_type_proto_rawDescOnce sync.Once
	file_agv_task_type_proto_rawDescData = file_agv_task_type_proto_rawDesc
)

func file_agv_task_type_proto_rawDescGZIP() []byte {
	file_agv_task_type_proto_rawDescOnce.Do(func() {
		file_agv_task_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_agv_task_type_proto_rawDescData)
	})
	return file_agv_task_type_proto_rawDescData
}

var file_agv_task_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agv_task_type_proto_goTypes = []interface{}{
	(*AGVTaskTypeInfo)(nil),              // 0: proto.AGVTaskTypeInfo
	(*QueryAGVTaskTypeRequest)(nil),      // 1: proto.QueryAGVTaskTypeRequest
	(*QueryAGVTaskTypeResponse)(nil),     // 2: proto.QueryAGVTaskTypeResponse
	(*GetAllAGVTaskTypeResponse)(nil),    // 3: proto.GetAllAGVTaskTypeResponse
	(*GetAGVTaskTypeDetailResponse)(nil), // 4: proto.GetAGVTaskTypeDetailResponse
	(*MaterialContainerTypeInfo)(nil),    // 5: proto.MaterialContainerTypeInfo
	(Code)(0),                            // 6: proto.Code
}
var file_agv_task_type_proto_depIdxs = []int32{
	5, // 0: proto.AGVTaskTypeInfo.materialContainerType:type_name -> proto.MaterialContainerTypeInfo
	6, // 1: proto.QueryAGVTaskTypeResponse.code:type_name -> proto.Code
	0, // 2: proto.QueryAGVTaskTypeResponse.data:type_name -> proto.AGVTaskTypeInfo
	6, // 3: proto.GetAllAGVTaskTypeResponse.code:type_name -> proto.Code
	0, // 4: proto.GetAllAGVTaskTypeResponse.data:type_name -> proto.AGVTaskTypeInfo
	6, // 5: proto.GetAGVTaskTypeDetailResponse.code:type_name -> proto.Code
	0, // 6: proto.GetAGVTaskTypeDetailResponse.data:type_name -> proto.AGVTaskTypeInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_agv_task_type_proto_init() }
func file_agv_task_type_proto_init() {
	if File_agv_task_type_proto != nil {
		return
	}
	file_mom_common_proto_init()
	file_material_container_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_agv_task_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AGVTaskTypeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agv_task_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAGVTaskTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agv_task_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAGVTaskTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agv_task_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllAGVTaskTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agv_task_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAGVTaskTypeDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agv_task_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agv_task_type_proto_goTypes,
		DependencyIndexes: file_agv_task_type_proto_depIdxs,
		MessageInfos:      file_agv_task_type_proto_msgTypes,
	}.Build()
	File_agv_task_type_proto = out.File
	file_agv_task_type_proto_rawDesc = nil
	file_agv_task_type_proto_goTypes = nil
	file_agv_task_type_proto_depIdxs = nil
}
