// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v3.21.12
// source: material_tray.proto

package proto

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// MaterialTrayClient is the client API for MaterialTray service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaterialTrayClient interface {
	Get(ctx context.Context, in *GetMaterialTrayRequest, opts ...grpc_go.CallOption) (*GetMaterialTrayDetailResponse, common.ErrorWithAttachment)
	Update(ctx context.Context, in *MaterialTrayInfo, opts ...grpc_go.CallOption) (*CommonResponse, common.ErrorWithAttachment)
}

type materialTrayClient struct {
	cc *triple.TripleConn
}

type MaterialTrayClientImpl struct {
	Get    func(ctx context.Context, in *GetMaterialTrayRequest) (*GetMaterialTrayDetailResponse, error)
	Update func(ctx context.Context, in *MaterialTrayInfo) (*CommonResponse, error)
}

func (c *MaterialTrayClientImpl) GetDubboStub(cc *triple.TripleConn) MaterialTrayClient {
	return NewMaterialTrayClient(cc)
}

func (c *MaterialTrayClientImpl) XXX_InterfaceName() string {
	return "proto.MaterialTray"
}

func NewMaterialTrayClient(cc *triple.TripleConn) MaterialTrayClient {
	return &materialTrayClient{cc}
}

func (c *materialTrayClient) Get(ctx context.Context, in *GetMaterialTrayRequest, opts ...grpc_go.CallOption) (*GetMaterialTrayDetailResponse, common.ErrorWithAttachment) {
	out := new(GetMaterialTrayDetailResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Get", in, out)
}

func (c *materialTrayClient) Update(ctx context.Context, in *MaterialTrayInfo, opts ...grpc_go.CallOption) (*CommonResponse, common.ErrorWithAttachment) {
	out := new(CommonResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Update", in, out)
}

// MaterialTrayServer is the server API for MaterialTray service.
// All implementations must embed UnimplementedMaterialTrayServer
// for forward compatibility
type MaterialTrayServer interface {
	Get(context.Context, *GetMaterialTrayRequest) (*GetMaterialTrayDetailResponse, error)
	Update(context.Context, *MaterialTrayInfo) (*CommonResponse, error)
	mustEmbedUnimplementedMaterialTrayServer()
}

// UnimplementedMaterialTrayServer must be embedded to have forward compatible implementations.
type UnimplementedMaterialTrayServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedMaterialTrayServer) Get(context.Context, *GetMaterialTrayRequest) (*GetMaterialTrayDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMaterialTrayServer) Update(context.Context, *MaterialTrayInfo) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (s *UnimplementedMaterialTrayServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedMaterialTrayServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedMaterialTrayServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &MaterialTray_ServiceDesc
}
func (s *UnimplementedMaterialTrayServer) XXX_InterfaceName() string {
	return "proto.MaterialTray"
}

func (UnimplementedMaterialTrayServer) mustEmbedUnimplementedMaterialTrayServer() {}

// UnsafeMaterialTrayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaterialTrayServer will
// result in compilation errors.
type UnsafeMaterialTrayServer interface {
	mustEmbedUnimplementedMaterialTrayServer()
}

func RegisterMaterialTrayServer(s grpc_go.ServiceRegistrar, srv MaterialTrayServer) {
	s.RegisterService(&MaterialTray_ServiceDesc, srv)
}

func _MaterialTray_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMaterialTrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Get", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _MaterialTray_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaterialTrayInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Update", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// MaterialTray_ServiceDesc is the grpc_go.ServiceDesc for MaterialTray service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaterialTray_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "proto.MaterialTray",
	HandlerType: (*MaterialTrayServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MaterialTray_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MaterialTray_Update_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "material_tray.proto",
}
