// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v3.21.12
// source: process_step_parameter.proto

package proto

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// ProcessStepParameterClient is the client API for ProcessStepParameter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessStepParameterClient interface {
	Query(ctx context.Context, in *QueryProcessStepParameterRequest, opts ...grpc_go.CallOption) (*QueryProcessStepParameterResponse, common.ErrorWithAttachment)
}

type processStepParameterClient struct {
	cc *triple.TripleConn
}

type ProcessStepParameterClientImpl struct {
	Query func(ctx context.Context, in *QueryProcessStepParameterRequest) (*QueryProcessStepParameterResponse, error)
}

func (c *ProcessStepParameterClientImpl) GetDubboStub(cc *triple.TripleConn) ProcessStepParameterClient {
	return NewProcessStepParameterClient(cc)
}

func (c *ProcessStepParameterClientImpl) XXX_InterfaceName() string {
	return "proto.ProcessStepParameter"
}

func NewProcessStepParameterClient(cc *triple.TripleConn) ProcessStepParameterClient {
	return &processStepParameterClient{cc}
}

func (c *processStepParameterClient) Query(ctx context.Context, in *QueryProcessStepParameterRequest, opts ...grpc_go.CallOption) (*QueryProcessStepParameterResponse, common.ErrorWithAttachment) {
	out := new(QueryProcessStepParameterResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Query", in, out)
}

// ProcessStepParameterServer is the server API for ProcessStepParameter service.
// All implementations must embed UnimplementedProcessStepParameterServer
// for forward compatibility
type ProcessStepParameterServer interface {
	Query(context.Context, *QueryProcessStepParameterRequest) (*QueryProcessStepParameterResponse, error)
	mustEmbedUnimplementedProcessStepParameterServer()
}

// UnimplementedProcessStepParameterServer must be embedded to have forward compatible implementations.
type UnimplementedProcessStepParameterServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedProcessStepParameterServer) Query(context.Context, *QueryProcessStepParameterRequest) (*QueryProcessStepParameterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (s *UnimplementedProcessStepParameterServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedProcessStepParameterServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedProcessStepParameterServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &ProcessStepParameter_ServiceDesc
}
func (s *UnimplementedProcessStepParameterServer) XXX_InterfaceName() string {
	return "proto.ProcessStepParameter"
}

func (UnimplementedProcessStepParameterServer) mustEmbedUnimplementedProcessStepParameterServer() {}

// UnsafeProcessStepParameterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessStepParameterServer will
// result in compilation errors.
type UnsafeProcessStepParameterServer interface {
	mustEmbedUnimplementedProcessStepParameterServer()
}

func RegisterProcessStepParameterServer(s grpc_go.ServiceRegistrar, srv ProcessStepParameterServer) {
	s.RegisterService(&ProcessStepParameter_ServiceDesc, srv)
}

func _ProcessStepParameter_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProcessStepParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Query", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessStepParameter_ServiceDesc is the grpc_go.ServiceDesc for ProcessStepParameter service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessStepParameter_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "proto.ProcessStepParameter",
	HandlerType: (*ProcessStepParameterServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _ProcessStepParameter_Query_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "process_step_parameter.proto",
}
