// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v3.21.12
// source: product_rework_record.proto

package proto

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// ProductReworkRecordClient is the client API for ProductReworkRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductReworkRecordClient interface {
	Add(ctx context.Context, in *ProductReworkRecordInfo, opts ...grpc_go.CallOption) (*CommonResponse, common.ErrorWithAttachment)
}

type productReworkRecordClient struct {
	cc *triple.TripleConn
}

type ProductReworkRecordClientImpl struct {
	Add func(ctx context.Context, in *ProductReworkRecordInfo) (*CommonResponse, error)
}

func (c *ProductReworkRecordClientImpl) GetDubboStub(cc *triple.TripleConn) ProductReworkRecordClient {
	return NewProductReworkRecordClient(cc)
}

func (c *ProductReworkRecordClientImpl) XXX_InterfaceName() string {
	return "proto.ProductReworkRecord"
}

func NewProductReworkRecordClient(cc *triple.TripleConn) ProductReworkRecordClient {
	return &productReworkRecordClient{cc}
}

func (c *productReworkRecordClient) Add(ctx context.Context, in *ProductReworkRecordInfo, opts ...grpc_go.CallOption) (*CommonResponse, common.ErrorWithAttachment) {
	out := new(CommonResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Add", in, out)
}

// ProductReworkRecordServer is the server API for ProductReworkRecord service.
// All implementations must embed UnimplementedProductReworkRecordServer
// for forward compatibility
type ProductReworkRecordServer interface {
	Add(context.Context, *ProductReworkRecordInfo) (*CommonResponse, error)
	mustEmbedUnimplementedProductReworkRecordServer()
}

// UnimplementedProductReworkRecordServer must be embedded to have forward compatible implementations.
type UnimplementedProductReworkRecordServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedProductReworkRecordServer) Add(context.Context, *ProductReworkRecordInfo) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (s *UnimplementedProductReworkRecordServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedProductReworkRecordServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedProductReworkRecordServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &ProductReworkRecord_ServiceDesc
}
func (s *UnimplementedProductReworkRecordServer) XXX_InterfaceName() string {
	return "proto.ProductReworkRecord"
}

func (UnimplementedProductReworkRecordServer) mustEmbedUnimplementedProductReworkRecordServer() {}

// UnsafeProductReworkRecordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductReworkRecordServer will
// result in compilation errors.
type UnsafeProductReworkRecordServer interface {
	mustEmbedUnimplementedProductReworkRecordServer()
}

func RegisterProductReworkRecordServer(s grpc_go.ServiceRegistrar, srv ProductReworkRecordServer) {
	s.RegisterService(&ProductReworkRecord_ServiceDesc, srv)
}

func _ProductReworkRecord_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductReworkRecordInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Add", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// ProductReworkRecord_ServiceDesc is the grpc_go.ServiceDesc for ProductReworkRecord service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductReworkRecord_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "proto.ProductReworkRecord",
	HandlerType: (*ProductReworkRecordServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _ProductReworkRecord_Add_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "product_rework_record.proto",
}
