// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v3.21.12
// source: product_model.proto

package proto

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// ProductModelClient is the client API for ProductModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductModelClient interface {
	GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc_go.CallOption) (*GetProductModelDetailResponse, common.ErrorWithAttachment)
}

type productModelClient struct {
	cc *triple.TripleConn
}

type ProductModelClientImpl struct {
	GetDetail func(ctx context.Context, in *GetDetailRequest) (*GetProductModelDetailResponse, error)
}

func (c *ProductModelClientImpl) GetDubboStub(cc *triple.TripleConn) ProductModelClient {
	return NewProductModelClient(cc)
}

func (c *ProductModelClientImpl) XXX_InterfaceName() string {
	return "proto.ProductModel"
}

func NewProductModelClient(cc *triple.TripleConn) ProductModelClient {
	return &productModelClient{cc}
}

func (c *productModelClient) GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc_go.CallOption) (*GetProductModelDetailResponse, common.ErrorWithAttachment) {
	out := new(GetProductModelDetailResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetDetail", in, out)
}

// ProductModelServer is the server API for ProductModel service.
// All implementations must embed UnimplementedProductModelServer
// for forward compatibility
type ProductModelServer interface {
	GetDetail(context.Context, *GetDetailRequest) (*GetProductModelDetailResponse, error)
	mustEmbedUnimplementedProductModelServer()
}

// UnimplementedProductModelServer must be embedded to have forward compatible implementations.
type UnimplementedProductModelServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedProductModelServer) GetDetail(context.Context, *GetDetailRequest) (*GetProductModelDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}
func (s *UnimplementedProductModelServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedProductModelServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedProductModelServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &ProductModel_ServiceDesc
}
func (s *UnimplementedProductModelServer) XXX_InterfaceName() string {
	return "proto.ProductModel"
}

func (UnimplementedProductModelServer) mustEmbedUnimplementedProductModelServer() {}

// UnsafeProductModelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductModelServer will
// result in compilation errors.
type UnsafeProductModelServer interface {
	mustEmbedUnimplementedProductModelServer()
}

func RegisterProductModelServer(s grpc_go.ServiceRegistrar, srv ProductModelServer) {
	s.RegisterService(&ProductModel_ServiceDesc, srv)
}

func _ProductModel_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetDetail", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// ProductModel_ServiceDesc is the grpc_go.ServiceDesc for ProductModel service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductModel_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "proto.ProductModel",
	HandlerType: (*ProductModelServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "GetDetail",
			Handler:    _ProductModel_GetDetail_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "product_model.proto",
}
