// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v3.21.12
// source: product_package_record.proto

package proto

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// ProductPackageRecordClient is the client API for ProductPackageRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductPackageRecordClient interface {
	Get(ctx context.Context, in *GetProductPackageRecordRequest, opts ...grpc_go.CallOption) (*GetProductPackageRecordDetailResponse, common.ErrorWithAttachment)
}

type productPackageRecordClient struct {
	cc *triple.TripleConn
}

type ProductPackageRecordClientImpl struct {
	Get func(ctx context.Context, in *GetProductPackageRecordRequest) (*GetProductPackageRecordDetailResponse, error)
}

func (c *ProductPackageRecordClientImpl) GetDubboStub(cc *triple.TripleConn) ProductPackageRecordClient {
	return NewProductPackageRecordClient(cc)
}

func (c *ProductPackageRecordClientImpl) XXX_InterfaceName() string {
	return "proto.ProductPackageRecord"
}

func NewProductPackageRecordClient(cc *triple.TripleConn) ProductPackageRecordClient {
	return &productPackageRecordClient{cc}
}

func (c *productPackageRecordClient) Get(ctx context.Context, in *GetProductPackageRecordRequest, opts ...grpc_go.CallOption) (*GetProductPackageRecordDetailResponse, common.ErrorWithAttachment) {
	out := new(GetProductPackageRecordDetailResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Get", in, out)
}

// ProductPackageRecordServer is the server API for ProductPackageRecord service.
// All implementations must embed UnimplementedProductPackageRecordServer
// for forward compatibility
type ProductPackageRecordServer interface {
	Get(context.Context, *GetProductPackageRecordRequest) (*GetProductPackageRecordDetailResponse, error)
	mustEmbedUnimplementedProductPackageRecordServer()
}

// UnimplementedProductPackageRecordServer must be embedded to have forward compatible implementations.
type UnimplementedProductPackageRecordServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedProductPackageRecordServer) Get(context.Context, *GetProductPackageRecordRequest) (*GetProductPackageRecordDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (s *UnimplementedProductPackageRecordServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedProductPackageRecordServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedProductPackageRecordServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &ProductPackageRecord_ServiceDesc
}
func (s *UnimplementedProductPackageRecordServer) XXX_InterfaceName() string {
	return "proto.ProductPackageRecord"
}

func (UnimplementedProductPackageRecordServer) mustEmbedUnimplementedProductPackageRecordServer() {}

// UnsafeProductPackageRecordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductPackageRecordServer will
// result in compilation errors.
type UnsafeProductPackageRecordServer interface {
	mustEmbedUnimplementedProductPackageRecordServer()
}

func RegisterProductPackageRecordServer(s grpc_go.ServiceRegistrar, srv ProductPackageRecordServer) {
	s.RegisterService(&ProductPackageRecord_ServiceDesc, srv)
}

func _ProductPackageRecord_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductPackageRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Get", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// ProductPackageRecord_ServiceDesc is the grpc_go.ServiceDesc for ProductPackageRecord service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductPackageRecord_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "proto.ProductPackageRecord",
	HandlerType: (*ProductPackageRecordServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ProductPackageRecord_Get_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "product_package_record.proto",
}
