// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: scada.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 采集设备（SCADA 网关连接的 PLC/仪表）
type ScadaDeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 代号
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 协议（modbus-tcp）
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// 地址（host:port）
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	// 从站号
	SlaveID int32 `protobuf:"varint,6,opt,name=slaveID,proto3" json:"slaveID,omitempty"`
	// 采集间隔（秒）
	IntervalSeconds int32 `protobuf:"varint,7,opt,name=intervalSeconds,proto3" json:"intervalSeconds,omitempty"`
	// 连接状态（正常/异常/未连接）
	ConnectionState string `protobuf:"bytes,8,opt,name=connectionState,proto3" json:"connectionState,omitempty"`
	// 最近一次采集时间
	LastCollectTime string `protobuf:"bytes,9,opt,name=lastCollectTime,proto3" json:"lastCollectTime,omitempty"`
	// 最近错误信息
	LastError string `protobuf:"bytes,10,opt,name=lastError,proto3" json:"lastError,omitempty"`
	// 是否启用
	Enable bool `protobuf:"varint,11,opt,name=enable,proto3" json:"enable,omitempty"`
	// 备注
	Remark string `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *ScadaDeviceInfo) Reset() {
	*x = ScadaDeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScadaDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScadaDeviceInfo) ProtoMessage() {}

func (x *ScadaDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScadaDeviceInfo.ProtoReflect.Descriptor instead.
func (*ScadaDeviceInfo) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{0}
}

func (x *ScadaDeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScadaDeviceInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ScadaDeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScadaDeviceInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ScadaDeviceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ScadaDeviceInfo) GetSlaveID() int32 {
	if x != nil {
		return x.SlaveID
	}
	return 0
}

func (x *ScadaDeviceInfo) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *ScadaDeviceInfo) GetConnectionState() string {
	if x != nil {
		return x.ConnectionState
	}
	return ""
}

func (x *ScadaDeviceInfo) GetLastCollectTime() string {
	if x != nil {
		return x.LastCollectTime
	}
	return ""
}

func (x *ScadaDeviceInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ScadaDeviceInfo) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ScadaDeviceInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type QueryScadaDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: uri:"pageIndex" form:"pageIndex"
	PageIndex int64 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty" uri:"pageIndex" form:"pageIndex"`
	// @inject_tag: uri:"pageSize" form:"pageSize"
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" uri:"pageSize" form:"pageSize"`
	// @inject_tag: uri:"sortConfig" form:"sortConfig"
	SortConfig string `protobuf:"bytes,3,opt,name=sortConfig,proto3" json:"sortConfig,omitempty" uri:"sortConfig" form:"sortConfig"`
	// 代号或名称
	// @inject_tag: uri:"code" form:"code"
	Code string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty" uri:"code" form:"code"`
}

func (x *QueryScadaDeviceRequest) Reset() {
	*x = QueryScadaDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryScadaDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScadaDeviceRequest) ProtoMessage() {}

func (x *QueryScadaDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScadaDeviceRequest.ProtoReflect.Descriptor instead.
func (*QueryScadaDeviceRequest) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{1}
}

func (x *QueryScadaDeviceRequest) GetPageIndex() int64 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *QueryScadaDeviceRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryScadaDeviceRequest) GetSortConfig() string {
	if x != nil {
		return x.SortConfig
	}
	return ""
}

func (x *QueryScadaDeviceRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type QueryScadaDeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code               `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code,omitempty"`
	Message string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*ScadaDeviceInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pages   int64              `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	Records int64              `protobuf:"varint,5,opt,name=records,proto3" json:"records,omitempty"`
	Total   int64              `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *QueryScadaDeviceResponse) Reset() {
	*x = QueryScadaDeviceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryScadaDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScadaDeviceResponse) ProtoMessage() {}

func (x *QueryScadaDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScadaDeviceResponse.ProtoReflect.Descriptor instead.
func (*QueryScadaDeviceResponse) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{2}
}

func (x *QueryScadaDeviceResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *QueryScadaDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryScadaDeviceResponse) GetData() []*ScadaDeviceInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryScadaDeviceResponse) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *QueryScadaDeviceResponse) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

func (x *QueryScadaDeviceResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAllScadaDeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code               `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code,omitempty"`
	Message string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*ScadaDeviceInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllScadaDeviceResponse) Reset() {
	*x = GetAllScadaDeviceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllScadaDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllScadaDeviceResponse) ProtoMessage() {}

func (x *GetAllScadaDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllScadaDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetAllScadaDeviceResponse) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllScadaDeviceResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *GetAllScadaDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllScadaDeviceResponse) GetData() []*ScadaDeviceInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetScadaDeviceDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code             `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code,omitempty"`
	Message string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *ScadaDeviceInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetScadaDeviceDetailResponse) Reset() {
	*x = GetScadaDeviceDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScadaDeviceDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScadaDeviceDetailResponse) ProtoMessage() {}

func (x *GetScadaDeviceDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScadaDeviceDetailResponse.ProtoReflect.Descriptor instead.
func (*GetScadaDeviceDetailResponse) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{4}
}

func (x *GetScadaDeviceDetailResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *GetScadaDeviceDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetScadaDeviceDetailResponse) GetData() *ScadaDeviceInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 采集点位
type ScadaTagInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 设备ID
	ScadaDeviceID   string `protobuf:"bytes,2,opt,name=scadaDeviceID,proto3" json:"scadaDeviceID,omitempty"`
	ScadaDeviceCode string `protobuf:"bytes,3,opt,name=scadaDeviceCode,proto3" json:"scadaDeviceCode,omitempty"`
	// 点位名称
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// 寄存器地址（十进制）
	Address int32 `protobuf:"varint,5,opt,name=address,proto3" json:"address,omitempty"`
	// 功能码（0-线圈 1-离散输入 3-保持寄存器 4-输入寄存器）
	FunctionCode int32 `protobuf:"varint,6,opt,name=functionCode,proto3" json:"functionCode,omitempty"`
	// 数据类型（bool/uint16/int16/float32）
	DataType string `protobuf:"bytes,7,opt,name=dataType,proto3" json:"dataType,omitempty"`
	// 缩放系数
	Scale float64 `protobuf:"fixed64,8,opt,name=scale,proto3" json:"scale,omitempty"`
	// 单位
	Unit string `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit,omitempty"`
	// 是否存历史
	SaveHistory bool `protobuf:"varint,10,opt,name=saveHistory,proto3" json:"saveHistory,omitempty"`
	// 是否启用
	Enable bool `protobuf:"varint,11,opt,name=enable,proto3" json:"enable,omitempty"`
	// 备注
	Remark string `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *ScadaTagInfo) Reset() {
	*x = ScadaTagInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScadaTagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScadaTagInfo) ProtoMessage() {}

func (x *ScadaTagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScadaTagInfo.ProtoReflect.Descriptor instead.
func (*ScadaTagInfo) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{5}
}

func (x *ScadaTagInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScadaTagInfo) GetScadaDeviceID() string {
	if x != nil {
		return x.ScadaDeviceID
	}
	return ""
}

func (x *ScadaTagInfo) GetScadaDeviceCode() string {
	if x != nil {
		return x.ScadaDeviceCode
	}
	return ""
}

func (x *ScadaTagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScadaTagInfo) GetAddress() int32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *ScadaTagInfo) GetFunctionCode() int32 {
	if x != nil {
		return x.FunctionCode
	}
	return 0
}

func (x *ScadaTagInfo) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ScadaTagInfo) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ScadaTagInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ScadaTagInfo) GetSaveHistory() bool {
	if x != nil {
		return x.SaveHistory
	}
	return false
}

func (x *ScadaTagInfo) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ScadaTagInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type QueryScadaTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: uri:"pageIndex" form:"pageIndex"
	PageIndex int64 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty" uri:"pageIndex" form:"pageIndex"`
	// @inject_tag: uri:"pageSize" form:"pageSize"
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" uri:"pageSize" form:"pageSize"`
	// @inject_tag: uri:"sortConfig" form:"sortConfig"
	SortConfig string `protobuf:"bytes,3,opt,name=sortConfig,proto3" json:"sortConfig,omitempty" uri:"sortConfig" form:"sortConfig"`
	// 设备ID
	// @inject_tag: uri:"scadaDeviceID" form:"scadaDeviceID"
	ScadaDeviceID string `protobuf:"bytes,4,opt,name=scadaDeviceID,proto3" json:"scadaDeviceID,omitempty" uri:"scadaDeviceID" form:"scadaDeviceID"`
	// 名称
	// @inject_tag: uri:"name" form:"name"
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty" uri:"name" form:"name"`
}

func (x *QueryScadaTagRequest) Reset() {
	*x = QueryScadaTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryScadaTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScadaTagRequest) ProtoMessage() {}

func (x *QueryScadaTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScadaTagRequest.ProtoReflect.Descriptor instead.
func (*QueryScadaTagRequest) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{6}
}

func (x *QueryScadaTagRequest) GetPageIndex() int64 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *QueryScadaTagRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryScadaTagRequest) GetSortConfig() string {
	if x != nil {
		return x.SortConfig
	}
	return ""
}

func (x *QueryScadaTagRequest) GetScadaDeviceID() string {
	if x != nil {
		return x.ScadaDeviceID
	}
	return ""
}

func (x *QueryScadaTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryScadaTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code            `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*ScadaTagInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pages   int64           `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	Records int64           `protobuf:"varint,5,opt,name=records,proto3" json:"records,omitempty"`
	Total   int64           `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *QueryScadaTagResponse) Reset() {
	*x = QueryScadaTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryScadaTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScadaTagResponse) ProtoMessage() {}

func (x *QueryScadaTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScadaTagResponse.ProtoReflect.Descriptor instead.
func (*QueryScadaTagResponse) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{7}
}

func (x *QueryScadaTagResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *QueryScadaTagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryScadaTagResponse) GetData() []*ScadaTagInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryScadaTagResponse) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *QueryScadaTagResponse) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

func (x *QueryScadaTagResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAllScadaTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code            `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*ScadaTagInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllScadaTagResponse) Reset() {
	*x = GetAllScadaTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllScadaTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllScadaTagResponse) ProtoMessage() {}

func (x *GetAllScadaTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllScadaTagResponse.ProtoReflect.Descriptor instead.
func (*GetAllScadaTagResponse) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllScadaTagResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *GetAllScadaTagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllScadaTagResponse) GetData() []*ScadaTagInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetScadaTagDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code          `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *ScadaTagInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetScadaTagDetailResponse) Reset() {
	*x = GetScadaTagDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScadaTagDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScadaTagDetailResponse) ProtoMessage() {}

func (x *GetScadaTagDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScadaTagDetailResponse.ProtoReflect.Descriptor instead.
func (*GetScadaTagDetailResponse) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{9}
}

func (x *GetScadaTagDetailResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *GetScadaTagDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetScadaTagDetailResponse) GetData() *ScadaTagInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 点位实时值
type ScadaTagValueInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 点位ID
	ScadaTagID string `protobuf:"bytes,1,opt,name=scadaTagID,proto3" json:"scadaTagID,omitempty"`
	TagName    string `protobuf:"bytes,2,opt,name=tagName,proto3" json:"tagName,omitempty"`
	Unit       string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	// 值（字符串表示）
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// 采集时间
	CollectTime string `protobuf:"bytes,5,opt,name=collectTime,proto3" json:"collectTime,omitempty"`
	// 质量（Good/Bad）
	Quality string `protobuf:"bytes,6,opt,name=quality,proto3" json:"quality,omitempty"`
}

func (x *ScadaTagValueInfo) Reset() {
	*x = ScadaTagValueInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScadaTagValueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScadaTagValueInfo) ProtoMessage() {}

func (x *ScadaTagValueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScadaTagValueInfo.ProtoReflect.Descriptor instead.
func (*ScadaTagValueInfo) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{10}
}

func (x *ScadaTagValueInfo) GetScadaTagID() string {
	if x != nil {
		return x.ScadaTagID
	}
	return ""
}

func (x *ScadaTagValueInfo) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *ScadaTagValueInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ScadaTagValueInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ScadaTagValueInfo) GetCollectTime() string {
	if x != nil {
		return x.CollectTime
	}
	return ""
}

func (x *ScadaTagValueInfo) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

type QueryScadaTagValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 设备ID（可选）
	// @inject_tag: uri:"scadaDeviceID" form:"scadaDeviceID"
	ScadaDeviceID string `protobuf:"bytes,1,opt,name=scadaDeviceID,proto3" json:"scadaDeviceID,omitempty" uri:"scadaDeviceID" form:"scadaDeviceID"`
}

func (x *QueryScadaTagValueRequest) Reset() {
	*x = QueryScadaTagValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryScadaTagValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScadaTagValueRequest) ProtoMessage() {}

func (x *QueryScadaTagValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScadaTagValueRequest.ProtoReflect.Descriptor instead.
func (*QueryScadaTagValueRequest) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{11}
}

func (x *QueryScadaTagValueRequest) GetScadaDeviceID() string {
	if x != nil {
		return x.ScadaDeviceID
	}
	return ""
}

type QueryScadaTagValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code                 `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code,omitempty"`
	Message string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*ScadaTagValueInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *QueryScadaTagValueResponse) Reset() {
	*x = QueryScadaTagValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryScadaTagValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScadaTagValueResponse) ProtoMessage() {}

func (x *QueryScadaTagValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScadaTagValueResponse.ProtoReflect.Descriptor instead.
func (*QueryScadaTagValueResponse) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{12}
}

func (x *QueryScadaTagValueResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *QueryScadaTagValueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryScadaTagValueResponse) GetData() []*ScadaTagValueInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 点位历史值
type ScadaTagHistoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 点位ID
	ScadaTagID  string `protobuf:"bytes,2,opt,name=scadaTagID,proto3" json:"scadaTagID,omitempty"`
	Value       string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CollectTime string `protobuf:"bytes,4,opt,name=collectTime,proto3" json:"collectTime,omitempty"`
}

func (x *ScadaTagHistoryInfo) Reset() {
	*x = ScadaTagHistoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScadaTagHistoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScadaTagHistoryInfo) ProtoMessage() {}

func (x *ScadaTagHistoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScadaTagHistoryInfo.ProtoReflect.Descriptor instead.
func (*ScadaTagHistoryInfo) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{13}
}

func (x *ScadaTagHistoryInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScadaTagHistoryInfo) GetScadaTagID() string {
	if x != nil {
		return x.ScadaTagID
	}
	return ""
}

func (x *ScadaTagHistoryInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ScadaTagHistoryInfo) GetCollectTime() string {
	if x != nil {
		return x.CollectTime
	}
	return ""
}

type QueryScadaTagHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: uri:"pageIndex" form:"pageIndex"
	PageIndex int64 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty" uri:"pageIndex" form:"pageIndex"`
	// @inject_tag: uri:"pageSize" form:"pageSize"
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" uri:"pageSize" form:"pageSize"`
	// @inject_tag: uri:"sortConfig" form:"sortConfig"
	SortConfig string `protobuf:"bytes,3,opt,name=sortConfig,proto3" json:"sortConfig,omitempty" uri:"sortConfig" form:"sortConfig"`
	// 点位ID
	// @inject_tag: uri:"scadaTagID" form:"scadaTagID"
	ScadaTagID string `protobuf:"bytes,4,opt,name=scadaTagID,proto3" json:"scadaTagID,omitempty" uri:"scadaTagID" form:"scadaTagID"`
	// 开始时间
	// @inject_tag: uri:"startTime" form:"startTime"
	StartTime string `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty" uri:"startTime" form:"startTime"`
	// 结束时间
	// @inject_tag: uri:"endTime" form:"endTime"
	EndTime string `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime,omitempty" uri:"endTime" form:"endTime"`
}

func (x *QueryScadaTagHistoryRequest) Reset() {
	*x = QueryScadaTagHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryScadaTagHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScadaTagHistoryRequest) ProtoMessage() {}

func (x *QueryScadaTagHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScadaTagHistoryRequest.ProtoReflect.Descriptor instead.
func (*QueryScadaTagHistoryRequest) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{14}
}

func (x *QueryScadaTagHistoryRequest) GetPageIndex() int64 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *QueryScadaTagHistoryRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryScadaTagHistoryRequest) GetSortConfig() string {
	if x != nil {
		return x.SortConfig
	}
	return ""
}

func (x *QueryScadaTagHistoryRequest) GetScadaTagID() string {
	if x != nil {
		return x.ScadaTagID
	}
	return ""
}

func (x *QueryScadaTagHistoryRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QueryScadaTagHistoryRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type QueryScadaTagHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*ScadaTagHistoryInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pages   int64                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	Records int64                  `protobuf:"varint,5,opt,name=records,proto3" json:"records,omitempty"`
	Total   int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *QueryScadaTagHistoryResponse) Reset() {
	*x = QueryScadaTagHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryScadaTagHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryScadaTagHistoryResponse) ProtoMessage() {}

func (x *QueryScadaTagHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryScadaTagHistoryResponse.ProtoReflect.Descriptor instead.
func (*QueryScadaTagHistoryResponse) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{15}
}

func (x *QueryScadaTagHistoryResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *QueryScadaTagHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryScadaTagHistoryResponse) GetData() []*ScadaTagHistoryInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryScadaTagHistoryResponse) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *QueryScadaTagHistoryResponse) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

func (x *QueryScadaTagHistoryResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 测试设备连接
type TestScadaDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 地址 host:port
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// 从站号
	SlaveID int32 `protobuf:"varint,2,opt,name=slaveID,proto3" json:"slaveID,omitempty"`
}

func (x *TestScadaDeviceRequest) Reset() {
	*x = TestScadaDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scada_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestScadaDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestScadaDeviceRequest) ProtoMessage() {}

func (x *TestScadaDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scada_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestScadaDeviceRequest.ProtoReflect.Descriptor instead.
func (*TestScadaDeviceRequest) Descriptor() ([]byte, []int) {
	return file_scada_proto_rawDescGZIP(), []int{16}
}

func (x *TestScadaDeviceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TestScadaDeviceRequest) GetSlaveID() int32 {
	if x != nil {
		return x.SlaveID
	}
	return 0
}

var File_scada_proto protoreflect.FileDescriptor

var file_scada_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x63, 0x61, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x6d, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x02, 0x0a, 0x0f, 0x53, 0x63, 0x61, 0x64, 0x61,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6c, 0x61, 0x76,
	0x65, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6c, 0x61, 0x76, 0x65,
	0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x28, 0x0a, 0x0f,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x87,
	0x01, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x18, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x82, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x63, 0x61,
	0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x85, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x61, 0x64, 0x61, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xd8, 0x02, 0x0a, 0x0c, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x24, 0x0a, 0x0d, 0x73, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x63, 0x61, 0x64, 0x61, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x73, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x61, 0x76, 0x65,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73,
	0x61, 0x76, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0xaa, 0x01, 0x0a, 0x14, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x0a,
	0x0d, 0x73, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xc1, 0x01, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x7c, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7f, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb3, 0x01, 0x0a, 0x11, 0x53,
	0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x22, 0x41, 0x0a, 0x19, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x73, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x44, 0x22, 0x85, 0x01, 0x0a, 0x1a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x61,
	0x64, 0x61, 0x54, 0x61, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7d, 0x0a, 0x13, 0x53,
	0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xcf, 0x01, 0x0a, 0x1b, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x61, 0x64, 0x61, 0x54,
	0x61, 0x67, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xcf, 0x01, 0x0a,
	0x1c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x63, 0x61, 0x64, 0x61, 0x54, 0x61, 0x67, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x4c,
	0x0a, 0x16, 0x54, 0x65, 0x73, 0x74, 0x53, 0x63, 0x61, 0x64, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x44, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scada_proto_rawDescOnce sync.Once
	file_scada_proto_rawDescData = file_scada_proto_rawDesc
)

func file_scada_proto_rawDescGZIP() []byte {
	file_scada_proto_rawDescOnce.Do(func() {
		file_scada_proto_rawDescData = protoimpl.X.CompressGZIP(file_scada_proto_rawDescData)
	})
	return file_scada_proto_rawDescData
}

var file_scada_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_scada_proto_goTypes = []interface{}{
	(*ScadaDeviceInfo)(nil),              // 0: proto.ScadaDeviceInfo
	(*QueryScadaDeviceRequest)(nil),      // 1: proto.QueryScadaDeviceRequest
	(*QueryScadaDeviceResponse)(nil),     // 2: proto.QueryScadaDeviceResponse
	(*GetAllScadaDeviceResponse)(nil),    // 3: proto.GetAllScadaDeviceResponse
	(*GetScadaDeviceDetailResponse)(nil), // 4: proto.GetScadaDeviceDetailResponse
	(*ScadaTagInfo)(nil),                 // 5: proto.ScadaTagInfo
	(*QueryScadaTagRequest)(nil),         // 6: proto.QueryScadaTagRequest
	(*QueryScadaTagResponse)(nil),        // 7: proto.QueryScadaTagResponse
	(*GetAllScadaTagResponse)(nil),       // 8: proto.GetAllScadaTagResponse
	(*GetScadaTagDetailResponse)(nil),    // 9: proto.GetScadaTagDetailResponse
	(*ScadaTagValueInfo)(nil),            // 10: proto.ScadaTagValueInfo
	(*QueryScadaTagValueRequest)(nil),    // 11: proto.QueryScadaTagValueRequest
	(*QueryScadaTagValueResponse)(nil),   // 12: proto.QueryScadaTagValueResponse
	(*ScadaTagHistoryInfo)(nil),          // 13: proto.ScadaTagHistoryInfo
	(*QueryScadaTagHistoryRequest)(nil),  // 14: proto.QueryScadaTagHistoryRequest
	(*QueryScadaTagHistoryResponse)(nil), // 15: proto.QueryScadaTagHistoryResponse
	(*TestScadaDeviceRequest)(nil),       // 16: proto.TestScadaDeviceRequest
	(Code)(0),                            // 17: proto.Code
}
var file_scada_proto_depIdxs = []int32{
	17, // 0: proto.QueryScadaDeviceResponse.code:type_name -> proto.Code
	0,  // 1: proto.QueryScadaDeviceResponse.data:type_name -> proto.ScadaDeviceInfo
	17, // 2: proto.GetAllScadaDeviceResponse.code:type_name -> proto.Code
	0,  // 3: proto.GetAllScadaDeviceResponse.data:type_name -> proto.ScadaDeviceInfo
	17, // 4: proto.GetScadaDeviceDetailResponse.code:type_name -> proto.Code
	0,  // 5: proto.GetScadaDeviceDetailResponse.data:type_name -> proto.ScadaDeviceInfo
	17, // 6: proto.QueryScadaTagResponse.code:type_name -> proto.Code
	5,  // 7: proto.QueryScadaTagResponse.data:type_name -> proto.ScadaTagInfo
	17, // 8: proto.GetAllScadaTagResponse.code:type_name -> proto.Code
	5,  // 9: proto.GetAllScadaTagResponse.data:type_name -> proto.ScadaTagInfo
	17, // 10: proto.GetScadaTagDetailResponse.code:type_name -> proto.Code
	5,  // 11: proto.GetScadaTagDetailResponse.data:type_name -> proto.ScadaTagInfo
	17, // 12: proto.QueryScadaTagValueResponse.code:type_name -> proto.Code
	10, // 13: proto.QueryScadaTagValueResponse.data:type_name -> proto.ScadaTagValueInfo
	17, // 14: proto.QueryScadaTagHistoryResponse.code:type_name -> proto.Code
	13, // 15: proto.QueryScadaTagHistoryResponse.data:type_name -> proto.ScadaTagHistoryInfo
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_scada_proto_init() }
func file_scada_proto_init() {
	if File_scada_proto != nil {
		return
	}
	file_mom_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_scada_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScadaDeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryScadaDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryScadaDeviceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllScadaDeviceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScadaDeviceDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScadaTagInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryScadaTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryScadaTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllScadaTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScadaTagDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScadaTagValueInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryScadaTagValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryScadaTagValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScadaTagHistoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryScadaTagHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryScadaTagHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scada_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestScadaDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scada_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scada_proto_goTypes,
		DependencyIndexes: file_scada_proto_depIdxs,
		MessageInfos:      file_scada_proto_msgTypes,
	}.Build()
	File_scada_proto = out.File
	file_scada_proto_rawDesc = nil
	file_scada_proto_goTypes = nil
	file_scada_proto_depIdxs = nil
}
