// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: system_event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSystemEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   string `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Enable bool   `protobuf:"varint,2,opt,name=enable,proto3" json:"enable"`
}

func (x *GetSystemEventRequest) Reset() {
	*x = GetSystemEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemEventRequest) ProtoMessage() {}

func (x *GetSystemEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemEventRequest.ProtoReflect.Descriptor instead.
func (*GetSystemEventRequest) Descriptor() ([]byte, []int) {
	return file_system_event_proto_rawDescGZIP(), []int{0}
}

func (x *GetSystemEventRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetSystemEventRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type SystemEventInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id"`
	// 代号
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code"`
	// 描述
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	// 是否启用
	Enable bool `protobuf:"varint,5,opt,name=enable,proto3" json:"enable"`
	// 系统事件参数
	SystemEventParameters []*SystemEventParameterInfo `protobuf:"bytes,6,rep,name=systemEventParameters,proto3" json:"systemEventParameters"`
	// 系统事件订阅
	SystemEventSubscriptions []*SystemEventSubscriptionInfo `protobuf:"bytes,7,rep,name=systemEventSubscriptions,proto3" json:"systemEventSubscriptions"`
}

func (x *SystemEventInfo) Reset() {
	*x = SystemEventInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemEventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEventInfo) ProtoMessage() {}

func (x *SystemEventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEventInfo.ProtoReflect.Descriptor instead.
func (*SystemEventInfo) Descriptor() ([]byte, []int) {
	return file_system_event_proto_rawDescGZIP(), []int{1}
}

func (x *SystemEventInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SystemEventInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SystemEventInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SystemEventInfo) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *SystemEventInfo) GetSystemEventParameters() []*SystemEventParameterInfo {
	if x != nil {
		return x.SystemEventParameters
	}
	return nil
}

func (x *SystemEventInfo) GetSystemEventSubscriptions() []*SystemEventSubscriptionInfo {
	if x != nil {
		return x.SystemEventSubscriptions
	}
	return nil
}

type SystemEventSubscriptionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 系统事件ID
	SystemEventID string `protobuf:"bytes,3,opt,name=systemEventID,proto3" json:"systemEventID"`
	// 远程服务任务ID
	RemoteServiceTaskID string `protobuf:"bytes,4,opt,name=remoteServiceTaskID,proto3" json:"remoteServiceTaskID"`
}

func (x *SystemEventSubscriptionInfo) Reset() {
	*x = SystemEventSubscriptionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemEventSubscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEventSubscriptionInfo) ProtoMessage() {}

func (x *SystemEventSubscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEventSubscriptionInfo.ProtoReflect.Descriptor instead.
func (*SystemEventSubscriptionInfo) Descriptor() ([]byte, []int) {
	return file_system_event_proto_rawDescGZIP(), []int{2}
}

func (x *SystemEventSubscriptionInfo) GetSystemEventID() string {
	if x != nil {
		return x.SystemEventID
	}
	return ""
}

func (x *SystemEventSubscriptionInfo) GetRemoteServiceTaskID() string {
	if x != nil {
		return x.RemoteServiceTaskID
	}
	return ""
}

type SystemEventParameterInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id"`
	// 数据类型
	DataType string `protobuf:"bytes,3,opt,name=dataType,proto3" json:"dataType"`
	// 名称
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	// 描述
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`
	// 参数值
	Value string `protobuf:"bytes,6,opt,name=value,proto3" json:"value"`
	// 系统事件ID
	SystemEventID string `protobuf:"bytes,7,opt,name=systemEventID,proto3" json:"systemEventID"`
}

func (x *SystemEventParameterInfo) Reset() {
	*x = SystemEventParameterInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemEventParameterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEventParameterInfo) ProtoMessage() {}

func (x *SystemEventParameterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEventParameterInfo.ProtoReflect.Descriptor instead.
func (*SystemEventParameterInfo) Descriptor() ([]byte, []int) {
	return file_system_event_proto_rawDescGZIP(), []int{3}
}

func (x *SystemEventParameterInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SystemEventParameterInfo) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *SystemEventParameterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemEventParameterInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SystemEventParameterInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SystemEventParameterInfo) GetSystemEventID() string {
	if x != nil {
		return x.SystemEventID
	}
	return ""
}

type QuerySystemEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: uri:"pageIndex" form:"pageIndex"
	PageIndex int64 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex" uri:"pageIndex" form:"pageIndex"`
	// @inject_tag: uri:"pageSize" form:"pageSize"
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize" uri:"pageSize" form:"pageSize"`
	// @inject_tag: uri:"sortConfig" form:"sortConfig"
	SortConfig string `protobuf:"bytes,3,opt,name=sortConfig,proto3" json:"sortConfig" uri:"sortConfig" form:"sortConfig"`
}

func (x *QuerySystemEventRequest) Reset() {
	*x = QuerySystemEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuerySystemEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySystemEventRequest) ProtoMessage() {}

func (x *QuerySystemEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySystemEventRequest.ProtoReflect.Descriptor instead.
func (*QuerySystemEventRequest) Descriptor() ([]byte, []int) {
	return file_system_event_proto_rawDescGZIP(), []int{4}
}

func (x *QuerySystemEventRequest) GetPageIndex() int64 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *QuerySystemEventRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QuerySystemEventRequest) GetSortConfig() string {
	if x != nil {
		return x.SortConfig
	}
	return ""
}

type QuerySystemEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code               `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code"`
	Message string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    []*SystemEventInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
	Pages   int64              `protobuf:"varint,4,opt,name=pages,proto3" json:"pages"`
	Records int64              `protobuf:"varint,5,opt,name=records,proto3" json:"records"`
	Total   int64              `protobuf:"varint,6,opt,name=total,proto3" json:"total"`
}

func (x *QuerySystemEventResponse) Reset() {
	*x = QuerySystemEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_event_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuerySystemEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySystemEventResponse) ProtoMessage() {}

func (x *QuerySystemEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_event_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySystemEventResponse.ProtoReflect.Descriptor instead.
func (*QuerySystemEventResponse) Descriptor() ([]byte, []int) {
	return file_system_event_proto_rawDescGZIP(), []int{5}
}

func (x *QuerySystemEventResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *QuerySystemEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QuerySystemEventResponse) GetData() []*SystemEventInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QuerySystemEventResponse) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *QuerySystemEventResponse) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

func (x *QuerySystemEventResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAllSystemEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code               `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code"`
	Message string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    []*SystemEventInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
}

func (x *GetAllSystemEventResponse) Reset() {
	*x = GetAllSystemEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_event_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSystemEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSystemEventResponse) ProtoMessage() {}

func (x *GetAllSystemEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_event_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSystemEventResponse.ProtoReflect.Descriptor instead.
func (*GetAllSystemEventResponse) Descriptor() ([]byte, []int) {
	return file_system_event_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllSystemEventResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *GetAllSystemEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllSystemEventResponse) GetData() []*SystemEventInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSystemEventDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code             `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Code" json:"code"`
	Message string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    *SystemEventInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (x *GetSystemEventDetailResponse) Reset() {
	*x = GetSystemEventDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_system_event_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemEventDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemEventDetailResponse) ProtoMessage() {}

func (x *GetSystemEventDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_event_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemEventDetailResponse.ProtoReflect.Descriptor instead.
func (*GetSystemEventDetailResponse) Descriptor() ([]byte, []int) {
	return file_system_event_proto_rawDescGZIP(), []int{7}
}

func (x *GetSystemEventDetailResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_None
}

func (x *GetSystemEventDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSystemEventDetailResponse) GetData() *SystemEventInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_system_event_proto protoreflect.FileDescriptor

var file_system_event_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x6d, 0x6f, 0x6d,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x22, 0xa6, 0x02, 0x0a, 0x0f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x55, 0x0a, 0x15, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x15, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x5e, 0x0a, 0x18, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x18, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x75, 0x0a, 0x1b, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x12, 0x30, 0x0a, 0x13, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x49, 0x44, 0x22, 0xb8, 0x01, 0x0a, 0x18, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x73, 0x0a,
	0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x22, 0xc7, 0x01, 0x0a, 0x18, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x82, 0x01, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x85, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x59, 0x0a, 0x0b, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_system_event_proto_rawDescOnce sync.Once
	file_system_event_proto_rawDescData = file_system_event_proto_rawDesc
)

func file_system_event_proto_rawDescGZIP() []byte {
	file_system_event_proto_rawDescOnce.Do(func() {
		file_system_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_system_event_proto_rawDescData)
	})
	return file_system_event_proto_rawDescData
}

var file_system_event_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_system_event_proto_goTypes = []interface{}{
	(*GetSystemEventRequest)(nil),        // 0: proto.GetSystemEventRequest
	(*SystemEventInfo)(nil),              // 1: proto.SystemEventInfo
	(*SystemEventSubscriptionInfo)(nil),  // 2: proto.SystemEventSubscriptionInfo
	(*SystemEventParameterInfo)(nil),     // 3: proto.SystemEventParameterInfo
	(*QuerySystemEventRequest)(nil),      // 4: proto.QuerySystemEventRequest
	(*QuerySystemEventResponse)(nil),     // 5: proto.QuerySystemEventResponse
	(*GetAllSystemEventResponse)(nil),    // 6: proto.GetAllSystemEventResponse
	(*GetSystemEventDetailResponse)(nil), // 7: proto.GetSystemEventDetailResponse
	(Code)(0),                            // 8: proto.Code
}
var file_system_event_proto_depIdxs = []int32{
	3, // 0: proto.SystemEventInfo.systemEventParameters:type_name -> proto.SystemEventParameterInfo
	2, // 1: proto.SystemEventInfo.systemEventSubscriptions:type_name -> proto.SystemEventSubscriptionInfo
	8, // 2: proto.QuerySystemEventResponse.code:type_name -> proto.Code
	1, // 3: proto.QuerySystemEventResponse.data:type_name -> proto.SystemEventInfo
	8, // 4: proto.GetAllSystemEventResponse.code:type_name -> proto.Code
	1, // 5: proto.GetAllSystemEventResponse.data:type_name -> proto.SystemEventInfo
	8, // 6: proto.GetSystemEventDetailResponse.code:type_name -> proto.Code
	1, // 7: proto.GetSystemEventDetailResponse.data:type_name -> proto.SystemEventInfo
	0, // 8: proto.SystemEvent.Get:input_type -> proto.GetSystemEventRequest
	7, // 9: proto.SystemEvent.Get:output_type -> proto.GetSystemEventDetailResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_system_event_proto_init() }
func file_system_event_proto_init() {
	if File_system_event_proto != nil {
		return
	}
	file_mom_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_system_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSystemEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemEventInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemEventSubscriptionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemEventParameterInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_event_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuerySystemEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_event_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuerySystemEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_event_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllSystemEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_system_event_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSystemEventDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_system_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_event_proto_goTypes,
		DependencyIndexes: file_system_event_proto_depIdxs,
		MessageInfos:      file_system_event_proto_msgTypes,
	}.Build()
	File_system_event_proto = out.File
	file_system_event_proto_rawDesc = nil
	file_system_event_proto_goTypes = nil
	file_system_event_proto_depIdxs = nil
}
