// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: weiapi_quality.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTestProjectWithParameterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 工位代号
	ProductionStation string `protobuf:"bytes,1,opt,name=productionStation,proto3" json:"productionStation"`
	// 托盘号
	TrayNo string `protobuf:"bytes,2,opt,name=trayNo,proto3" json:"trayNo"`
	// 产品序列号
	ProductSerialNo string `protobuf:"bytes,3,opt,name=productSerialNo,proto3" json:"productSerialNo"`
}

func (x *GetTestProjectWithParameterRequest) Reset() {
	*x = GetTestProjectWithParameterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weiapi_quality_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestProjectWithParameterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestProjectWithParameterRequest) ProtoMessage() {}

func (x *GetTestProjectWithParameterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weiapi_quality_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestProjectWithParameterRequest.ProtoReflect.Descriptor instead.
func (*GetTestProjectWithParameterRequest) Descriptor() ([]byte, []int) {
	return file_weiapi_quality_proto_rawDescGZIP(), []int{0}
}

func (x *GetTestProjectWithParameterRequest) GetProductionStation() string {
	if x != nil {
		return x.ProductionStation
	}
	return ""
}

func (x *GetTestProjectWithParameterRequest) GetTrayNo() string {
	if x != nil {
		return x.TrayNo
	}
	return ""
}

func (x *GetTestProjectWithParameterRequest) GetProductSerialNo() string {
	if x != nil {
		return x.ProductSerialNo
	}
	return ""
}

type GetTestProjectWithParameterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    *TestProjectWithParameterInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (x *GetTestProjectWithParameterResponse) Reset() {
	*x = GetTestProjectWithParameterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weiapi_quality_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestProjectWithParameterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestProjectWithParameterResponse) ProtoMessage() {}

func (x *GetTestProjectWithParameterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weiapi_quality_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestProjectWithParameterResponse.ProtoReflect.Descriptor instead.
func (*GetTestProjectWithParameterResponse) Descriptor() ([]byte, []int) {
	return file_weiapi_quality_proto_rawDescGZIP(), []int{1}
}

func (x *GetTestProjectWithParameterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTestProjectWithParameterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTestProjectWithParameterResponse) GetData() *TestProjectWithParameterInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type TestProjectWithParameterInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestProjects     []*TestProjectInfo `protobuf:"bytes,1,rep,name=testProjects,proto3" json:"testProjects"`
	InputParameters  []*ParameterInfo   `protobuf:"bytes,2,rep,name=inputParameters,proto3" json:"inputParameters"`
	OutputParameters []*ParameterInfo   `protobuf:"bytes,3,rep,name=outputParameters,proto3" json:"outputParameters"`
}

func (x *TestProjectWithParameterInfo) Reset() {
	*x = TestProjectWithParameterInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weiapi_quality_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProjectWithParameterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProjectWithParameterInfo) ProtoMessage() {}

func (x *TestProjectWithParameterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_weiapi_quality_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProjectWithParameterInfo.ProtoReflect.Descriptor instead.
func (*TestProjectWithParameterInfo) Descriptor() ([]byte, []int) {
	return file_weiapi_quality_proto_rawDescGZIP(), []int{2}
}

func (x *TestProjectWithParameterInfo) GetTestProjects() []*TestProjectInfo {
	if x != nil {
		return x.TestProjects
	}
	return nil
}

func (x *TestProjectWithParameterInfo) GetInputParameters() []*ParameterInfo {
	if x != nil {
		return x.InputParameters
	}
	return nil
}

func (x *TestProjectWithParameterInfo) GetOutputParameters() []*ParameterInfo {
	if x != nil {
		return x.OutputParameters
	}
	return nil
}

type TestProjectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Code        string `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
}

func (x *TestProjectInfo) Reset() {
	*x = TestProjectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weiapi_quality_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProjectInfo) ProtoMessage() {}

func (x *TestProjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_weiapi_quality_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProjectInfo.ProtoReflect.Descriptor instead.
func (*TestProjectInfo) Descriptor() ([]byte, []int) {
	return file_weiapi_quality_proto_rawDescGZIP(), []int{3}
}

func (x *TestProjectInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestProjectInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TestProjectInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ParameterInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectCode   string `protobuf:"bytes,1,opt,name=projectCode,proto3" json:"projectCode"`
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	StandardValue string `protobuf:"bytes,4,opt,name=standardValue,proto3" json:"standardValue"`
	MinimumValue  string `protobuf:"bytes,5,opt,name=minimumValue,proto3" json:"minimumValue"`
	MaximumValue  string `protobuf:"bytes,6,opt,name=maximumValue,proto3" json:"maximumValue"`
	Unit          string `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit"`
	GroupCode     string `protobuf:"bytes,8,opt,name=groupCode,proto3" json:"groupCode"`
}

func (x *ParameterInfo) Reset() {
	*x = ParameterInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weiapi_quality_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParameterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterInfo) ProtoMessage() {}

func (x *ParameterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_weiapi_quality_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterInfo.ProtoReflect.Descriptor instead.
func (*ParameterInfo) Descriptor() ([]byte, []int) {
	return file_weiapi_quality_proto_rawDescGZIP(), []int{4}
}

func (x *ParameterInfo) GetProjectCode() string {
	if x != nil {
		return x.ProjectCode
	}
	return ""
}

func (x *ParameterInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ParameterInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParameterInfo) GetStandardValue() string {
	if x != nil {
		return x.StandardValue
	}
	return ""
}

func (x *ParameterInfo) GetMinimumValue() string {
	if x != nil {
		return x.MinimumValue
	}
	return ""
}

func (x *ParameterInfo) GetMaximumValue() string {
	if x != nil {
		return x.MaximumValue
	}
	return ""
}

func (x *ParameterInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ParameterInfo) GetGroupCode() string {
	if x != nil {
		return x.GroupCode
	}
	return ""
}

var File_weiapi_quality_proto protoreflect.FileDescriptor

var file_weiapi_quality_proto_rawDesc = []byte{
	0x0a, 0x14, 0x77, 0x65, 0x69, 0x61, 0x70, 0x69, 0x5f, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x01,
	0x0a, 0x22, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x11, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x79, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x72, 0x61, 0x79, 0x4e, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x4e, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x69, 0x74, 0x68,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xdc, 0x01, 0x0a, 0x1c, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3a, 0x0a, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x12, 0x3e, 0x0a, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x40, 0x0a, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x22, 0x57, 0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x87, 0x02, 0x0a, 0x0d,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6d,
	0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_weiapi_quality_proto_rawDescOnce sync.Once
	file_weiapi_quality_proto_rawDescData = file_weiapi_quality_proto_rawDesc
)

func file_weiapi_quality_proto_rawDescGZIP() []byte {
	file_weiapi_quality_proto_rawDescOnce.Do(func() {
		file_weiapi_quality_proto_rawDescData = protoimpl.X.CompressGZIP(file_weiapi_quality_proto_rawDescData)
	})
	return file_weiapi_quality_proto_rawDescData
}

var file_weiapi_quality_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_weiapi_quality_proto_goTypes = []interface{}{
	(*GetTestProjectWithParameterRequest)(nil),  // 0: proto.GetTestProjectWithParameterRequest
	(*GetTestProjectWithParameterResponse)(nil), // 1: proto.GetTestProjectWithParameterResponse
	(*TestProjectWithParameterInfo)(nil),        // 2: proto.TestProjectWithParameterInfo
	(*TestProjectInfo)(nil),                     // 3: proto.TestProjectInfo
	(*ParameterInfo)(nil),                       // 4: proto.ParameterInfo
}
var file_weiapi_quality_proto_depIdxs = []int32{
	2, // 0: proto.GetTestProjectWithParameterResponse.data:type_name -> proto.TestProjectWithParameterInfo
	3, // 1: proto.TestProjectWithParameterInfo.testProjects:type_name -> proto.TestProjectInfo
	4, // 2: proto.TestProjectWithParameterInfo.inputParameters:type_name -> proto.ParameterInfo
	4, // 3: proto.TestProjectWithParameterInfo.outputParameters:type_name -> proto.ParameterInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_weiapi_quality_proto_init() }
func file_weiapi_quality_proto_init() {
	if File_weiapi_quality_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_weiapi_quality_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestProjectWithParameterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weiapi_quality_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestProjectWithParameterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weiapi_quality_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProjectWithParameterInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weiapi_quality_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProjectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_weiapi_quality_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParameterInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_weiapi_quality_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weiapi_quality_proto_goTypes,
		DependencyIndexes: file_weiapi_quality_proto_depIdxs,
		MessageInfos:      file_weiapi_quality_proto_msgTypes,
	}.Build()
	File_weiapi_quality_proto = out.File
	file_weiapi_quality_proto_rawDesc = nil
	file_weiapi_quality_proto_goTypes = nil
	file_weiapi_quality_proto_depIdxs = nil
}
